name: Build site

on:
  push:
    branches: [ php-update ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Setup PHP with composer v2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer:v2

    - name: Get Composer Cache Directory.
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
      shell: bash

    - name: Cache composer packages.
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Cache node modules.
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Update composer dependencies
      run: composer update --prefer-dist --no-progress --no-suggest

    - name: Inject access token in .npmrc.
      run: |
        echo "@helsingborg-stad:registry=https://npm.pkg.github.com/helsingborg-stad" >> ~/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

    - name: Get ACF
      run: |
        wget "${{ secrets.ACF_URL }}" -O acf.zip
        unzip acf.zip -d wp-content/plugins/
        rm acf.zip

    - name: Execute buildscripts in themes and plugins folders
      run: php ./build.php --cleanup

    - name: Cleanup .npmrc
      run: rm ~/.npmrc

    - name: rsync deployment to www-data user.
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzrog --rsync-path="sudo rsync" --delete --chown=litespeed:litespeed --chmod=g+rw --exclude config --exclude wp-content/uploads --exclude wp-content/plugins/gravityforms --exclude wp-content/plugins/wp-schema-pro --exclude track-assets --exclude wp-content/plugins/volontar-wordpress --exclude wp-content/languages
        path: .
        remote_path: ${{ secrets.DEPLOY_REMOTE_PATH_JELASTIC }}
        remote_host: ${{ secrets.DEPLOY_REMOTE_HOST_JELASTIC }}
        remote_user: ${{ secrets.DEPLOY_REMOTE_USER_JELASTIC }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
        remote_port: ${{ secrets.DEPLOY_REMOTE_PORT_JELASTIC }}
